export const INITIAL_CLIENTS = [
  {
    id: "c1",
    full_name: "María Fernández",
    email: "maria.fernandez@email.com",
    phone: "+54 9 11 4523-8890",
    address: "Av. Corrientes 2450, CABA",
    role: "Cliente",
    status: "activo",
    created_at: "2024-01-15",
  },
  {
    id: "c2",
    full_name: "Carlos Rodríguez",
    email: "carlos.rodriguez@email.com",
    phone: "+54 9 11 6789-1234",
    address: "Calle Moldes 1820, Belgrano",
    role: "Cliente",
    status: "activo",
    created_at: "2024-02-01",
  },
  {
    id: "c3",
    full_name: "Lucía Morales",
    email: "lucia.morales@email.com",
    phone: "+54 9 11 3412-9900",
    address: "Calle Palermo 430, CABA",
    role: "Cliente",
    status: "activo",
    created_at: "2024-03-10",
  },
  {
    id: "c4",
    full_name: "Gonzalo Benítez",
    email: "gonzalo.benitez@email.com",
    phone: "+54 9 11 8876-4321",
    address: "Av. Santa Fe 3100, Palermo",
    role: "Cliente",
    status: "activo",
    created_at: "2024-04-20",
  },
];

export const VETERINARIANS = [
  { id: "v1", full_name: "Dr. Mateo Gómez", specialization: "Cirugía y Medicina General", role: "Veterinario" },
  { id: "v2", full_name: "Dra. Valeria Rossi", specialization: "Dermatología y Vacunación", role: "Veterinario" },
  { id: "v3", full_name: "Dr. Santiago Silva", specialization: "Radiología e Internación", role: "Veterinario" },
];

export const INITIAL_PETS = [
  {
    id: "p1",
    name: "Apolo",
    species: "Perro",
    breed: "Golden Retriever",
    sex: "Macho",
    age_years: 4,
    birth_date: "2020-05-12",
    weight_kg: 31.5,
    color: "Dorado",
    photo_url: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400",
    microchip: "CHIP-985141029",
    owner_id: "c1",
    owner_name: "María Fernández",
    notes: "Muy dócil, sensible al alimento con pollo.",
    status: "activo",
  },
  {
    id: "p2",
    name: "Luna",
    species: "Gato",
    breed: "Siamés",
    sex: "Hembra",
    age_years: 2,
    birth_date: "2022-08-20",
    weight_kg: 4.2,
    color: "Crema y Café",
    photo_url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=400",
    microchip: "CHIP-441209312",
    owner_id: "c2",
    owner_name: "Carlos Rodríguez",
    notes: "Vacunas al día, algo asustadiza.",
    status: "activo",
  },
  {
    id: "p3",
    name: "Thor",
    species: "Perro",
    breed: "Bulldog Francés",
    sex: "Macho",
    age_years: 3,
    birth_date: "2021-11-03",
    weight_kg: 12.8,
    color: "Atigrado",
    photo_url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=400",
    microchip: "CHIP-110948322",
    owner_id: "c3",
    owner_name: "Lucía Morales",
    notes: "Problemas respiratorios leves de raza.",
    status: "activo",
  },
  {
    id: "p4",
    name: "Simba",
    species: "Gato",
    breed: "Persa",
    sex: "Macho",
    age_years: 5,
    birth_date: "2019-03-15",
    weight_kg: 5.1,
    color: "Naranja",
    photo_url: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=400",
    microchip: "CHIP-773419082",
    owner_id: "c4",
    owner_name: "Gonzalo Benítez",
    notes: "Requiere cepillado frecuente.",
    status: "activo",
  },
];

export const INITIAL_MEDICAL_RECORDS = [
  {
    id: "m1",
    pet_id: "p1",
    pet_name: "Apolo",
    vet_id: "v1",
    vet_name: "Dr. Mateo Gómez",
    record_date: "2024-05-10",
    type: "Consulta General",
    title: "Chequeo Anual y Control de Peso",
    description: "Paciente en excelente estado de salud general. Mucosas rosadas, reflejos normales.",
    diagnosis: "Saludable",
    treatment: "Mantener dieta baja en grasas y ejercicio moderado.",
    medication_prescribed: "Pipeta antipulgas mensual",
    attachment_url: "",
  },
  {
    id: "m2",
    pet_id: "p2",
    pet_name: "Luna",
    vet_id: "v2",
    vet_name: "Dra. Valeria Rossi",
    record_date: "2024-06-02",
    type: "Diagnóstico",
    title: "Cuadro Dermatológico en Orejas",
    description: "Presenta rascado continuo e irritación en oreja izquierda.",
    diagnosis: "Otitis fúngica leve",
    treatment: "Limpieza auricular 2 veces al día por 7 días.",
    medication_prescribed: "Gotas Otológicas con Ketoconazol y Dexametasona",
    attachment_url: "",
  },
  {
    id: "m3",
    pet_id: "p3",
    pet_name: "Thor",
    vet_id: "v3",
    vet_name: "Dr. Santiago Silva",
    record_date: "2024-07-14",
    type: "Cirugía",
    title: "Corrección de Narinas Esctenóticas",
    description: "Procedimiento quirúrgico para mejorar flujo aéreo nasal.",
    diagnosis: "Síndrome Braquicefálico",
    treatment: "Reposo absoluto de 10 días con collar isabelino.",
    medication_prescribed: "Meloxicam 1mg/ml, Cephalexina 250mg",
    attachment_url: "",
  },
];

export const INITIAL_APPOINTMENTS = [
  {
    id: "a1",
    pet_id: "p1",
    pet_name: "Apolo",
    client_id: "c1",
    client_name: "María Fernández",
    vet_id: "v1",
    vet_name: "Dr. Mateo Gómez",
    appointment_date: "2026-08-14",
    appointment_time: "10:00",
    reason: "Refuerzo de Vacuna Sextuple",
    status: "confirmado",
    notes: "Traer libreta sanitaria.",
  },
  {
    id: "a2",
    pet_id: "p2",
    pet_name: "Luna",
    client_id: "c2",
    client_name: "Carlos Rodríguez",
    vet_id: "v2",
    vet_name: "Dra. Valeria Rossi",
    appointment_date: "2026-08-14",
    appointment_time: "11:30",
    reason: "Control de Otitis",
    status: "solicitado",
    notes: "Segunda revisión post tratamiento.",
  },
  {
    id: "a3",
    pet_id: "p3",
    pet_name: "Thor",
    client_id: "c3",
    client_name: "Lucía Morales",
    vet_id: "v3",
    vet_name: "Dr. Santiago Silva",
    appointment_date: "2026-08-15",
    appointment_time: "16:00",
    reason: "Extracción de Puntos de Sutura",
    status: "confirmado",
    notes: "Post-cirugía.",
  },
  {
    id: "a4",
    pet_id: "p4",
    pet_name: "Simba",
    client_id: "c4",
    client_name: "Gonzalo Benítez",
    vet_id: "v1",
    vet_name: "Dr. Mateo Gómez",
    appointment_date: "2026-08-18",
    appointment_time: "09:30",
    reason: "Limpieza Dental y Sarro",
    status: "solicitado",
    notes: "Requiere ayuno de 8 horas.",
  },
];

export const INITIAL_VACCINES = [
  {
    id: "vcc1",
    pet_id: "p1",
    pet_name: "Apolo",
    owner_name: "María Fernández",
    vaccine_name: "Séxtuple Canina",
    application_date: "2025-08-15",
    next_due_date: "2026-08-15", // Próxima a vencer
    vet_id: "v1",
    vet_name: "Dr. Mateo Gómez",
    status: "pendiente",
    notes: "Alerta de vacuna por vencer en 2 días.",
  },
  {
    id: "vcc2",
    pet_id: "p2",
    pet_name: "Luna",
    owner_name: "Carlos Rodríguez",
    vaccine_name: "Triple Felina",
    application_date: "2026-01-10",
    next_due_date: "2027-01-10",
    vet_id: "v2",
    vet_name: "Dra. Valeria Rossi",
    status: "aplicada",
    notes: "Sin reacciones adversas.",
  },
  {
    id: "vcc3",
    pet_id: "p3",
    pet_name: "Thor",
    owner_name: "Lucía Morales",
    vaccine_name: "Antirrábica",
    application_date: "2025-08-20",
    next_due_date: "2026-08-20", // Próxima a vencer
    vet_id: "v3",
    vet_name: "Dr. Santiago Silva",
    status: "pendiente",
    notes: "Notificación enviada al cliente.",
  },
  {
    id: "vcc4",
    pet_id: "p4",
    pet_name: "Simba",
    owner_name: "Gonzalo Benítez",
    vaccine_name: "Leucemia Felina (FeLV)",
    application_date: "2026-03-05",
    next_due_date: "2027-03-05",
    vet_id: "v2",
    vet_name: "Dra. Valeria Rossi",
    status: "aplicada",
    notes: "Test previo negativo.",
  },
];

export const INITIAL_HOSPITALIZATIONS = [
  {
    id: "h1",
    pet_id: "p3",
    pet_name: "Thor",
    species: "Perro",
    owner_name: "Lucía Morales",
    vet_id: "v3",
    vet_name: "Dr. Santiago Silva",
    admission_date: "2026-08-12",
    discharge_date: null,
    reason: "Monitoreo post-quirúrgico y manejo del dolor nasal",
    daily_evolution: "Evolución favorable. Mantiene constante de oxígeno normal. Aceptó comida blanda.",
    treatment: "Fluido-terapia Ringer Lactato, Analgesia IV cada 8hs.",
    status: "activa",
  },
];

export const INITIAL_PHARMACY = [
  {
    id: "ph1",
    name: "Amoxicilina + Ácido Clavulánico 500mg",
    description: "Antibiótico de amplio espectro para caninos y felinos.",
    category: "Antibiótico",
    stock: 4,
    min_stock: 10, // Stock bajo
    unit_price: 4500,
    supplier: "Laboratorio VetPharma",
    expiration_date: "2027-02-15",
  },
  {
    id: "ph2",
    name: "Meloxicam Gotas 0.5%",
    description: "Antiinflamatorio no esteroideo (AINE) para gatos y perros.",
    category: "Analgesia",
    stock: 18,
    min_stock: 5,
    unit_price: 3200,
    supplier: "Zoetis Argentina",
    expiration_date: "2026-11-30",
  },
  {
    id: "ph3",
    name: "Vacuna Antirrábica Nobivac",
    description: "Frasco ampolla monodosis 1ml.",
    category: "Biológico",
    stock: 3,
    min_stock: 15, // Stock bajo
    unit_price: 6800,
    supplier: "MSD Animal Health",
    expiration_date: "2026-09-01",
  },
  {
    id: "ph4",
    name: "Shampoo Antiséptico Chlorhexidine 3%",
    description: "Higiene dermatológica para piodermias.",
    category: "Dermatología",
    stock: 12,
    min_stock: 4,
    unit_price: 5400,
    supplier: "Bayer Animal",
    expiration_date: "2028-05-10",
  },
];
